### ISSUE TITLE
There is no test for this project

### ISSUE THREAD

**Issue by secondstriker** [codinginflow/MVVMNewsApp#1]
There is no test for this project. This isn't we expected.
The true way for developing is testing each step and then go to next step.

**Comment by codinginflow** [comment]
Hey,
testing is out of scope for this course because it's a huge topic that I can't just cover on the side. I am planning to create a separate course for it in the future where I can cover it in detail.
I can refund your purchase but I didn't find your name in the course students. Did you buy the course?

**Comment by codinginflow** [comment]
Closed because no further response. As said, testing will be covered separately.
